# Generated by Django 5.0 on 2024-04-05 18:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("UserAccount", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Company"},
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "Driver"},
        ),
        migrations.AlterModelOptions(
            name="transporter",
            options={"verbose_name": "Transporter"},
        ),
        migrations.AlterModelOptions(
            name="vehicle",
            options={"verbose_name": "Vehicle"},
        ),
        migrations.AlterModelOptions(
            name="vehicleowner",
            options={"verbose_name": "Vehicle Owner"},
        ),
        migrations.RenameField(
            model_name="driver",
            old_name="Aadhar",
            new_name="aadhar",
        ),
        migrations.RenameField(
            model_name="transporter",
            old_name="Aadhar",
            new_name="aadhar",
        ),
        migrations.RenameField(
            model_name="transporter",
            old_name="BuiltiNumber",
            new_name="builti_number",
        ),
        migrations.RenameField(
            model_name="transporter",
            old_name="Pan_Card",
            new_name="pan_card",
        ),
        migrations.RenameField(
            model_name="transporter",
            old_name="Transport_Name",
            new_name="transport_name",
        ),
        migrations.RenameField(
            model_name="transporter",
            old_name="Vehicle_Under_Control",
            new_name="vehicle_under_control",
        ),
        migrations.RenameField(
            model_name="vehicle",
            old_name="Vehicle_Number",
            new_name="vehicle_number",
        ),
        migrations.RenameField(
            model_name="vehiclerequest",
            old_name="Requeststatus",
            new_name="request_status",
        ),
        migrations.RenameField(
            model_name="vehiclerequest",
            old_name="Transporter",
            new_name="transporter",
        ),
        migrations.RenameField(
            model_name="vehiclerequest",
            old_name="Vehicle",
            new_name="vehicle",
        ),
        migrations.RenameField(
            model_name="vehiclerequest",
            old_name="Vehicle_Owner",
            new_name="vehicle_owner",
        ),
    ]
