# Generated by Django 5.0 on 2024-04-09 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserAccount", "0002_alter_company_options_alter_driver_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_vehicles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
