# Generated by Django 5.0 on 2024-04-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserAccount", "0003_alter_vehicle_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="UserType",
            field=models.IntegerField(
                choices=[
                    (1, "Company"),
                    (2, "Transporter"),
                    (3, "Vehicle Owner"),
                    (4, "Driver"),
                ]
            ),
        ),
    ]
