# Generated by Django 5.0 on 2024-04-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserAccount", "0004_alter_customuser_usertype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="Company_Name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Company Name"
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="aadhar",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Aadhar number"
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="license",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="license number"
            ),
        ),
        migrations.AlterField(
            model_name="transporter",
            name="aadhar",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Aadhar number"
            ),
        ),
        migrations.AlterField(
            model_name="transporter",
            name="pan_card",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Pan Card"
            ),
        ),
        migrations.AlterField(
            model_name="transporter",
            name="transport_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Transport Name"
            ),
        ),
    ]
