# Generated by Django 5.0 on 2024-04-27 06:57

import django.db.models.deletion
import django.utils.timezone
import sales.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("UserAccount", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallanTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "challan_number",
                    models.DecimalField(decimal_places=0, max_digits=10),
                ),
                ("material", models.CharField(max_length=30, null=True)),
                (
                    "Weight_at_loading",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "Weight_at_unloading",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=10
                    ),
                ),
                (
                    "loading_dt",
                    models.DateField(blank=True, default=django.utils.timezone.now),
                ),
                ("unloading_dt", models.DateField(blank=True, null=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="unloaded_at",
                        to="UserAccount.company",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="UserAccount.driver",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="Loaded_from",
                        to="UserAccount.company",
                    ),
                ),
                (
                    "transporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="transporter",
                        to="UserAccount.transporter",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="UserAccount.vehicle",
                    ),
                ),
            ],
            bases=(models.Model, sales.utils.InvoiceLineMixin),
        ),
    ]
